import { withAuth } from "next-auth/middleware"
export default withAuth({
  pages: {
    signIn: "/login",
  },
})
export const config = {  matcher: [
    "/",
    "/Configurations",
    "/Configurations/priveleges",
    "/Configurations/system-settings",
    "/MasterData",
    "/MasterData/VehicleMake",
    "/MasterData/Country",
    "/MasterData/DriverNeededDocumentation",
    "/serviceLocations",
    "/Admin",
    "/PickupRequests",
    "/PickupRequests/CompletedPickups",
    "/PickupRequests/PendingPickups",
    "/PickupRequests/CancelledPickups",
    "/PickupRequests/OngoingPickups",
    "/PickupRequests/ExpiredPickups",
    "/manageDrivers",
    "/manageDrivers/ApprovedDrivers",
    "/manageDrivers/ApprovePendingDrivers",
    "/manageDrivers/DriverRatings",
    "/manageDrivers/NegativeBalanceDrivers",
    "/manageUsers",
    "/manageUsers/ApprovedUsers",
    "/manageUsers/ApprovePendingUsers",
    "/manageUsers/SuspendedUsers",
    "/manageUsers/DeactivatedUsers",
    "/manageUsers/DeletedUsers",
    "/Chat",
    "/Notification",
    "/PromoCode",
    "/Complaints",
    "/Complaints/UserComplaint",
    "/Complaints/DriverComplaint",
    "/Reports",
    "/Reports/UserReport",
    "/Reports/DriverReport",
    "/Reports/FinanceReport",
  ],
}
